# Generated by Django 3.2.7 on 2021-10-06 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogdev', '0004_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
