# Generated by Django 3.2.7 on 2021-10-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdev', '0006_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
